namespace babl
{
    public enum BablId
    {
        Undefined = 0,
        TypeBase = 100,
        U8,
        U16,
        U32,
        Half,
        Float,
        Double,
        HalfFloat,

        U8Luma,
        U8Chroma,
        U16CieL,
        U16CieAb,
        U8CieL,
        U8CieAb,
        TypeLastInternal,

        ModelBase = 1000,
        Gray,
        GrayAlpha,
        GrayAlphaPremultiplied,
        Rgb,
        Rgba,
        RgbaPremultiplied,
        ModelGrayNonlinear,
        ModelGrayNonlinearAlpha,
        ModelGrayNonlinearAlphaPremultiplied,
        ModelGrayPerceptual,
        ModelGrayPerceptualAlpha,
        ModelGrayPerceptualAlphaPremultiplied,
        RgbNonlinear,
        RgbaNonlinear,
        RgbaNonlinearPremultiplied,
        RgbPerceptual,
        RgbaPerceptual,
        RgbaPerceptualPremultiplied,
        Ycbcr,
        YcbcrAlpha,
        CieLab,
        CieLabAlpha,
        ModelLastInternal,

        ComponentBase = 10000,
        GrayLinear,
        GrayLinearMulAlpha,
        Red,
        Green,
        Blue,
        Alpha,
        RedMulAlpha,
        GreenMulAlpha,
        BlueMulAlpha,
        GrayPerceptual,
        GrayPerceptualMulAlpha,
        GrayNonlinear,
        GrayNonlinearMulAlpha,
        Red_Nonlinear,
        GreenNonlinear,
        BlueNonlinear,
        RedNonlinearMulAlpha,
        GreenNonlinearMulAlpha,
        BlueNonlinearMulAlpha,
        Red_Perceptual,
        Green_Perceptual,
        Blue_Perceptual,
        Red_PerceptualMulAlpha,
        Green_PerceptualMulAlpha,
        Blue_PerceptualMulAlpha,


        X,
        Y,
        Z,
        CieL,
        CieA,
        CieB,
        Cb,
        Cr,
        Padding,
        ComponentLastInternal,

        FormatBase = 100000,
        Srbb,
        Srgba,
        RgbHalf,
        RgbaHalf,
        RgbFloat,
        RgbaFloat,
        RgbaDouble,
        LabFloat,
        LabU16,
        LabU8,
        RgbU8,
        RgbaU8,
        RgbaU16,
        CmykHalf,
        CmykFloat,
        CmykAlphaFloat,
        CmykAlphaHalf,
        Ycbcr411,
        Ycbcr422,
        Ycbcr420,
        FormatLastInternal,

        PixelUserBase
    }
}
