name: Build, Test, Deploy

env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CORE_SDK_VERSION: 5.0.100-rc.2.20479.15
  SOLUTION_PATH: './babl/babl.sln'

on:
  push:
    branches: [master, develop]
    tags: [v*]
  pull_request:
    branches: [master, develop]
  repository_dispatch:
    types: [run]

jobs:
  build-test-pack-job:
    name: 'Build, test & pack solution'
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]

    steps:
    - name: "Download NuGetVersion version artifact"
      uses: actions/download-artifact@v2
      with:
        name: nuget-version

    - name: "Read NuGetVersion artifact"
      id: version
      shell: bash
      run: |
        ls -a
        export NUGET_VERSION=$(cat nuget-version.txt)
        echo ::set-output name=nuGetVersion::$NUGET_VERSION


    - name: "Checkout repository"
      uses: actions/checkout@master
      with:
        submodules: true
        lfs: true

    - name: "Setup .NET Core CLI"
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '${{ env.DOTNET_CORE_SDK_VERSION }}'

    - name: "Install fonts (Ubuntu)"
      if: matrix.os == 'ubuntu.latest'
      run: |
        echo "ttf-mscorefonts-installer msttcorefonts/accepted-mscorefonts-eula select true" | sudo debconf-set-selections
        sudo apt-get install -y ttf-mscorefonts-installer
        sudo apt-get install -y fontconfig
        sudo fc-cache -f -v
        sudo fc-match Arial

    - name: "Instal dependencies"
      run: dotnet restore '${{ env.SOLUTION_PATH }}' --verbosity quiet

    - name: "Build solution"
      run: dotnet build '${{ env.SOLUTION_PATH }}' --nologo --verbosity minimal --configuration Release --no-restore /p:Version=${{ steps.version.outputs.nuGetVersion }}

    - name: "Test solution"
      run: dotnet test '${{ env.SOLUTION_PATH }}' --nologo --verbosity normal --configuration Release --no-build

    - name: "Pack solution"
      if: matrix.os == 'ubuntu-latest'
      run: dotnet pack '${{ env.SOLUTION_PATH }}' --nologo --output './nuget-packages' --verbosity minimal --configuration Release --no-build -p:PackageVersion=${{ steps.version.outputs.nuGetVersion }}

    - name: 'Upload packed artifacts'
      if: matrix.os == 'ubuntu-latest'
      uses: actions/upload-artifact@v2
      with:
        name: nuget-packages
        path: './nurget-packages/*/**'